[package]
name = "tinylang-rs"
version = "0.1.0"
authors = ["IWANABETHATGUY <974153916@qq.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
