name: Build and Deploy
on: # 监听 master 分支上的 push 事件
  push:
    branches:
      - master
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest # 构建环境使用 ubuntu
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.1  
        with:
          persist-credentials: false

      - name: Install and Build # 下载依赖 打包项目
        run: |
          cd ./wasm/www
          npm install
          npm run build

      - name: Deploy # 将打包内容发布到 github page
        uses: JamesIves/github-pages-deploy-action@3.5.9
        with:  # 自定义环境变量
          ACCESS_TOKEN: ${{ secrets.TINYLANG_RS }} 
          BRANCH: master
          FOLDER: wasm/www/dist
          REPOSITORY_NAME: IWANABETHATGUY/tinylang-rs
          TARGET_FOLDER: docs
          CLEAN: true 
