name: test

on:
  push:
    branches: [ master, pull_request ]
  pull_request:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2.3.1
      - name: install rust nightly  
        uses: actions-rs/toolchain@v1
        with:
          persist-credentials: false
          toolchain: nightly
          override: true
          
      - name: run  test
        run: cargo test --verbose
